import '@/style/index.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Header from '@/components/Header'
import Provider from '@/store/Provider'
import mongoose from 'mongoose'

// connect to db
mongoose.connect(process.env.MONGODB_URI!)
  .then(() => console.log("connected to db"))

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}